name: Update Files Version Field
description: Update your files version field on new releases
author: Pocket Apps
branding:
  color: blue
  icon: arrow-up-circle
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  branch:
    required: true
    description: Branch to push the changes to
    default: 'main'
